### ISSUE TITLE
2.06 As an admin, I want to save results of batch mode tests to a file.

### ISSUE THREAD

**Issue by morlick** [CMPUT401-Find-an-Expert/Find-an-Expert#13]
So basically an endpoint (eg. /batch) that takes in a query and approach, then outputs json of keywords?

**Comment by DT9** [comment]
Since we're already saving all keywords to elastic, and admins have access to kibana.
I think an admin could simply dump all keywords with just GET /keywords/

**Comment by GarryBullock** [comment]
We have access to Kibana in our development environment. It won't be exposed when running on cybera. All communication with elastic has to be done through our service.

**Comment by DT9** [comment]
https://github.com/CMPUT401-Find-an-Expert/BFEX/blob/master/web/bfex/blueprints/batch_api.py
