### ISSUE TITLE
Key Gen: freebie approach

### ISSUE THREAD

**Issue by MandyMeindersma** [CMPUT401-Find-an-Expert/Find-an-Expert#55]

**Comment by DT9** [comment]
hey guys, what has to be done here again?

**Comment by MandyMeindersma** [comment]
in the model document there is a "user_keywords" section. That is where we store all the freebies. It needs to be put the the keyword model with their own approach id

**Comment by MandyMeindersma** [comment]
replace with the general approach cause it sucks
